name: Build agregado afiliación

on:
  push:
    paths:
      - 'input/**'
      - 'scripts/**'
      - '.github/workflows/aggregate.yml'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip

      - name: Run aggregator
        run: |
          python scripts/aggregate.py

      - name: Commit aggregated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/agregado.csv data/agregado.json || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(agregado): actualizar datos"
            git push
          else
            echo "No changes to commit"
          fi
